# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4a89a1edcb914751e4ee6369f8edb6cf6462b884464351939c60c8ee04cb9c38d3ee43ba3158ee772376f26ba49df85a12ce1c8577f42943fe5297034cd411

test:
  secret_key_base: 6060ae71013f2f0908a73251cac5ff7a5b8df22ca2088b941fef071b317ed2d777e5a42e9627772cab4b2d460f576a2754cb18c9bfaad865591235ecec0f0d35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
